### ISSUE TITLE
Buggy, does not work with 8x8 tiles

### ISSUE THREAD

**Issue by luRaichu** [andremichelle/platforms#4]
I'm a Game Boy game developer, but to limitations I can only use 192 individual tiles per stage. I designed a map in an image editing program, but it contains too many tiles. I tried to use your tool to reduce the number of tiles in the map-image, but it doesn't work correctly with 8x8 tiles, and sometimes the Recreation does not show up.
![tiles-5](https://user-images.githubusercontent.com/69605426/102790402-62a1c100-4373-11eb-8575-50d637d084a5.png)
![tilemap](https://user-images.githubusercontent.com/69605426/102790420-6897a200-4373-11eb-9b75-b169b96de3cd.png)

**Comment by andremichelle** [comment]
Fixed
